export { TypeHandler } from "./TypeHandler"
import "./card-csc"
import "./card-expires"
import "./card-number"
import "./text"
import "./zip-code"
import "./password"
import "./email"
import "./price"
