import { Component, h, Host, VNode } from "@stencil/core"

@Component({
	tag: "smoothly-next-demo",
	styleUrl: "style.css",
	scoped: true,
})
export class SmoothlyNextDemo {
	render(): VNode | VNode[] {
		return (
			<Host>
				<smoothly-next-table columns={2}>
					<smoothly-next-table-head>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Header Cell</smoothly-next-table-cell>
							<smoothly-next-table-cell>Header Cell</smoothly-next-table-cell>
						</smoothly-next-table-row>
					</smoothly-next-table-head>
					<smoothly-next-table-body>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell1</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2</smoothly-next-table-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-expandable-row>
							<div slot={"detail"}>Content of the expandable row</div>
							<smoothly-next-table-cell>Cell1 in expandable row</smoothly-next-table-cell>
							<smoothly-next-table-cell>Cell2 in expandable row</smoothly-next-table-cell>
						</smoothly-next-table-expandable-row>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Cell5</smoothly-next-table-cell>
							<smoothly-next-table-expandable-cell>
								Expandable Cell
								<div slot={"detail"}>Content of the expandable cell</div>
							</smoothly-next-table-expandable-cell>
						</smoothly-next-table-row>
						<smoothly-next-table-row>
							<smoothly-next-table-expandable-cell>
								Expandable Cell 1<div slot={"detail"}>Content of the expandable cell 1</div>
							</smoothly-next-table-expandable-cell>
							<smoothly-next-table-expandable-cell>
								Expandable Cell 2<div slot={"detail"}>Content of the expandable cell 2</div>
							</smoothly-next-table-expandable-cell>
						</smoothly-next-table-row>
					</smoothly-next-table-body>
					<smoothly-next-table-foot>
						<smoothly-next-table-row>
							<smoothly-next-table-cell>Footer Cell</smoothly-next-table-cell>
							<smoothly-next-table-cell>Footer Cell</smoothly-next-table-cell>
						</smoothly-next-table-row>
					</smoothly-next-table-foot>
				</smoothly-next-table>
			</Host>
		)
	}
}
